# Generated by Django 4.2.7 on 2023-11-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPlayList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('discription', models.TextField(null=True)),
                ('qty', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
