print("Доброе время суток ")
user = input("Введите ваше Имя и Фамилию: ")
print(user + " Добро пожаловать! ")
old = input(user + " Ваш возраст?: ")
print(old)
gender = input(user + " Ваш пол?: ")
print(gender)
work = input(user + " Ваше место работы?: ")
print(work)
college = input(user + " Ваше место учебы?: ")
print(college)
grade = input(user + " Ваш курс обучения?: ")
print(grade)
course = input(user + " Направление вашего обучения?: ")
print(course)
experience = input(user + " Изучали ли программирование раннее?: ")
print(experience)
cash = input(user + " Ваша желаемая зарплата?: ")
print(cash)
input(" Спасибо за ответы ")